name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move EXE to Release
        run: |
          mkdir -p release
          mv Password Generator\Objects\PasswordGenerator.exe release/PasswordGenerator.exe
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0
          release_name: Release v1.0
          body: |
            This is the first release of PasswordGenerator.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
